### PR TITLE
Get 1.17 in workflow

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
What about 1.17.1 instead?

**Comment by u9g** [comment]
> What about 1.17.1 instead?

The idea is to use minecraft-packets in prismarine-proxy, so ideally we would need both, but I was thinking maybe we do 1.17 and prismarine-proxy can point at the major version ( since I don't think packets change between minor versions)

**Comment by rom1504** [comment]
Packets do change between minor versions
1.17.1 could be the reference for 1.17 no ?

**Comment by u9g** [comment]
> Packets do change between minor versions

Oh I wasn't aware.

> 1.17.1 could be the reference for 1.17 no ?

Then we have to have a reference table, for what versions correspond to what packets.

**Pull request merged**
